### ISSUE TITLE
Run `mfa align ...` get python error

### ISSUE THREAD

**Issue by mythg** [openvpi/MakeDiffSinger#10]
When I run `mfa align ../../sample/ ../../opencpop-extension.txt ../../mfa-opencpop-extension.zip ../../textgrids/result --beam 100 --clean --overwrite` command, I get the error below:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/advance/miniconda3/envs/mfa/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 122, in align_corpus_cli
    aligner.align()
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 327, in align
    self.initialize_database()
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/abc.py", line 288, in initialize_database
    MfaSqlBase.metadata.create_all(self.db_engine)
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/abc.py", line 294, in db_engine
    self._db_engine = self.construct_engine()
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/montreal_forced_aligner/abc.py", line 387, in construct_engine
    e = sqlalchemy.create_engine(
  File "<string>", line 2, in create_engine
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/advance/miniconda3/envs/mfa/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 636, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'pool_size','max_overflow' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

Then I try to change montreal_forced_aligner/abc.py:
 kwargs["pool_size"] = 5
 kwargs["max_overflow"] = 10

But it still have same problem. How can i resolve it?

**Comment by yqzhishen** [comment]
Are you using the right version of MFA? Or do you have non-ASCII filenames?
