### ISSUE TITLE
推断音高值报错

### ISSUE THREAD

**Issue by laiyoi** [openvpi/MakeDiffSinger#5]
(diff) PS E:\DiffSinger\data> python .\estimate_midi.py .\liuchan_23.06.25\raw\transcriptions.csv .\liuchan_23.06.25\raw\wavs
  0%|                                                                                         | 0/1689 [00:00<?, ?it/s]E:\DiffSinger\data\get_pitch.py:6: RuntimeWarning: divide by zero encountered in log2
  f0 = np.log2(f0)
  0%|                                                                                 | 1/1689 [00:00<07:19,  3.84it/s]E:\anaconda\envs\diff\lib\site-packages\librosa\core\convert.py:740: RuntimeWarning: divide by zero encountered in log2
  return 12 * (np.log2(np.asanyarray(frequencies)) - np.log2(440.0)) + 69
 52%|████████████████████████████████████████▎                                     | 872/1689 [00:07<00:05, 142.78it/s].\estimate_midi.py:66: RuntimeWarning: invalid value encountered in cast
  counts = np.bincount(np.round(word_pitch).astype(np.int64))
 52%|████████████████████████████████████████▊                                     | 884/1689 [00:07<00:06, 123.33it/s]
Traceback (most recent call last):
  File ".\estimate_midi.py", line 84, in <module>
    estimate_midi()
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".\estimate_midi.py", line 66, in estimate_midi
    counts = np.bincount(np.round(word_pitch).astype(np.int64))
  File "<__array_function__ internals>", line 200, in bincount
ValueError: 'list' argument must have no negative elements

**Comment by laiyoi** [comment]
更新了还是不行
``` 
Traceback (most recent call last):
  File "estimate_midi.py", line 84, in <module>
    estimate_midi()
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "estimate_midi.py", line 65, in estimate_midi
    word_pitch = np.extract(~word_uv & word_pitch >= 0, word_pitch)
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by yqzhishen** [comment]
不好意思，现在应该完全修复了

**Comment by laiyoi** [comment]
在处理之前报错的文件时出现了新的报错
(diff) PS E:\DiffSinger\data> python .\estimate_midi.py .\liuchan_23.06.26\raw\transcriptions.csv .\liuchan_23.06.26\raw\wavs\
  0%|                                                                                         | 0/1689 [00:00<?, ?it/s]E:\DiffSinger\data\get_pitch.py:6: RuntimeWarning: divide by zero encountered in log2
  f0 = np.log2(f0)
E:\anaconda\envs\diff\lib\site-packages\librosa\core\convert.py:740: RuntimeWarning: divide by zero encountered in log2
  return 12 * (np.log2(np.asanyarray(frequencies)) - np.log2(440.0)) + 69
 52%|████████████████████████████████████████▊                                     | 884/1689 [00:07<00:06, 118.83it/s]
Traceback (most recent call last):
  File ".\estimate_midi.py", line 84, in <module>
    estimate_midi()
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\anaconda\envs\diff\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".\estimate_midi.py", line 67, in estimate_midi
    midi = counts.argmax()
ValueError: attempt to get argmax of an empty sequence

**Comment by laiyoi** [comment]
目前不报错了但是转换成ds文件之后用SlurCutter查看发现很多音符变成了虚线的(b4c08ee之前不这样，之前只有少量是)，貌似是因为很多被标记成了rest，这样是合理的吗。SlurCutte中也不能改虚线的，要改成实心的只能手改ds和csv文件
是这句```if np.sum(uv[start_idx: end_idx]) >= rest_uv_ratio * (end_idx - start_idx):```的问题吗 `b4c08ee`后他被改成了`if len(word_valid_pitch) < rest_uv_ratio * (end_idx - start_idx):`我改成了<=也没有用

**Comment by yqzhishen** [comment]
这里按道理应该是没问题了的，能提供一下截图么，或者对应的音频和ds文件

**Comment by laiyoi** [comment]
这是图片
![屏幕截图 2023-06-26 231455](https://github.com/openvpi/MakeDiffSinger/assets/117524251/0ba2c945-fc5b-4ccc-8ff3-5d527a0dbf21)
![屏幕截图 2023-06-26 231500](https://github.com/openvpi/MakeDiffSinger/assets/117524251/6c4b852c-dc62-4a6a-bea6-47d8f6f98f98)

**Comment by laiyoi** [comment]
![image](https://github.com/openvpi/MakeDiffSinger/assets/117524251/050d8921-8ed2-4dfa-8a21-cf0d6212adc3)

**Comment by yqzhishen** [comment]
确实有问题，修好了

![image](https://github.com/openvpi/MakeDiffSinger/assets/70186231/c4751ff0-0f5b-4688-aabb-ac86f8791418)
